In [ ]:
import json
from pathlib import Path

import pandas as pd

import re

from collections import Counter

from transformers import CLIPModel, CLIPProcessor

import torch
import torch.nn.functional as F
from PIL import Image
import os
from tqdm import tqdm

import numpy as np

In [133]:
DATA_DIR  = Path("../Dataset/JSON")
IMAGE_DIR = Path("../Dataset/dataset_image")

IMAGE_DATA_DIR = Path("../Dataset/dataset_image")

OUTPUT_DIR = Path("../Output")

MODEL_NAME="openai/clip-vit-large-patch14-336"

DEVICE = "cpu"

PATCH_SIZE = 14

In [134]:
model = CLIPModel.from_pretrained(MODEL_NAME)
processor = CLIPProcessor.from_pretrained(MODEL_NAME)
model.eval()

Loading weights: 100%|██████████| 590/590 [00:00<00:00, 35727.64it/s]
CLIPModel LOAD REPORT from: openai/clip-vit-large-patch14-336
Key                                  | Status     |  |
-------------------------------------+------------+--+-
vision_model.embeddings.position_ids | UNEXPECTED |  |
text_model.embeddings.position_ids   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

CLIPModel(
  (text_model): CLIPTextTransformer(
    (embeddings): CLIPTextEmbeddings(
      (token_embedding): Embedding(49408, 768)
      (position_embedding): Embedding(77, 768)
    )
    (encoder): CLIPEncoder(
      (layers): ModuleList(
        (0-11): 12 x CLIPEncoderLayer(
          (self_attn): CLIPAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (layer_norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (mlp): CLIPMLP(
            (activation_fn): QuickGELUActivation()
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
          )
          (layer_norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
    (final_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (vision_model): CLIPVisionTransformer(
    (embeddings): CLIPVisionEmbeddings(
      (patch_embedding): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
      (position_embedding): Embedding(577, 1024)
    )
    (pre_layrnorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (encoder): CLIPEncoder(
      (layers): ModuleList(
        (0-23): 24 x CLIPEncoderLayer(
          (self_attn): CLIPAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (layer_norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (mlp): CLIPMLP(
            (activation_fn): QuickGELUActivation()
            (fc1): Linear(in_features=1024, out_features=4096, bias=True)
            (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          )
          (layer_norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
    (post_layernorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
  )
  (visual_projection): Linear(in_features=1024, out_features=768, bias=False)
  (text_projection): Linear(in_features=768, out_features=768, bias=False)
)

In [135]:
with open(DATA_DIR / "test.json", encoding="utf-8") as f:
    test_data = json.load(f)

with open(DATA_DIR / "valid.json", encoding="utf-8") as f:
    val_data = json.load(f)

with open(DATA_DIR / "train.json", encoding="utf-8") as f:
    train_data = json.load(f)

df_test = pd.DataFrame(test_data)
df_val = pd.DataFrame(val_data)
df_train = pd.DataFrame(train_data)

print(f"Train Data Length: {len(df_train)}")
print(f"Validation Data Length: {len(df_val)}")
print(f"Test Data Length: {len(df_test)}")
df_train.head(5)

Train Data Length: 19816
Validation Data Length: 2410
Test Data Length: 2409

,image_id,text,label
0,840006160660983809,<user> thanks for showing up for our appointme...,1
1,908913372199915520,haha .,1
2,916496521406726145,i love waiting <num> min for a cab - such shor...,1
3,916364004129304576,22 super funny quotes <user>,1
4,853866052589154304,goog morning,1

In [136]:
df_master = pd.concat([df_test, df_train, df_val])
print(len(df_master))

24635

In [137]:
word_list = set()
for text in df_master["text"]:
    words = text.split(" ")
    for word in words:
        text_0 = re.findall(r'<[^>]*>', word)
        if len(text_0) != 0:
            word_list.add(word)

print(word_list)

{'<num>', '<facepalm>', '<>', '<user>', '<<url>'}

In [138]:
tag_counts = Counter()
for text in df_master["text"]:
    for word in str(text).split():
        if re.fullmatch(r'<[^>]*>', word):
            tag_counts[word] += 1

print(tag_counts.most_common())

[('<user>', 8629), ('<num>', 577), ('<>', 2), ('<<url>', 1), ('<facepalm>', 1)]

In [139]:
image_path = IMAGE_DATA_DIR / "682716753374351360.jpg"
print(image_path)
sample_image = Image.open(image_path).convert("RGB")

sample_image.size

..\Dataset\dataset_image\682716753374351360.jpg

(800, 563)

In [140]:
inputs = processor(images=sample_image, return_tensors="pt")
pixel_values = inputs["pixel_values"].to(DEVICE)

print("Shape: ", pixel_values.shape)

Shape:  torch.Size([1, 3, 336, 336])

In [141]:
patches = pixel_values.unfold(2, PATCH_SIZE, PATCH_SIZE).unfold(3, PATCH_SIZE, PATCH_SIZE)
print(patches.shape)
patches = patches.permute(0,2,3,1,4,5)
print(patches.shape)
patches = patches.reshape(1,576,3,14,14)
print(patches.shape)

torch.Size([1, 3, 24, 24, 14, 14])
torch.Size([1, 24, 24, 3, 14, 14])
torch.Size([1, 576, 3, 14, 14])

In [142]:
#List of patches dimana pixel steiap patchesnya sudah di flatten
flat_patches = patches.reshape(1, 576, -1)
print("Flatten Patches: ", flat_patches.shape)

Flatten Patches:  torch.Size([1, 576, 588])

In [143]:
with torch.no_grad():
    vision = model.vision_model
    emb = vision.embeddings

    patch_grid = emb.patch_embedding(pixel_values)
    print(patch_grid.shape)
    patch_embeddings = patch_grid.flatten(2).transpose(1, 2)
    print("patch emb: ", patch_embeddings.shape)
    batch_size = patch_embeddings.shape[0]
    print("emb class: ", emb.class_embedding.shape)
    cls_token = emb.class_embedding.expand(batch_size, 1, -1)
    print(cls_token.shape)

    token_emb = torch.concat([patch_embeddings, cls_token], dim=1)
    print("total token: ", token_emb.shape)

    position_ids = torch.arange(token_emb.shape[1], device=pixel_values.device).unsqueeze(0)
    position_embeddings = emb.position_embedding(position_ids)

    final_embedding = token_emb + position_embeddings
    print("position_embeddings:", position_embeddings.shape)
    print("final_embedding:", final_embedding.shape)

    hidden_states = vision.pre_layrnorm(final_embedding)
    encoder_outputs = vision.encoder(
        inputs_embeds=hidden_states,
        output_hidden_states=True,
        return_dict=True
    )

    visual_features = encoder_outputs.last_hidden_state
    print("visual features shape: ", visual_features.shape)
    cls_output = visual_features[:, 0, :]
    print("cls_output before post norm:", cls_output.shape)

    embv_1024 = vision.post_layernorm(cls_output)
    print("EmbV 1024:", embv_1024.shape)

    embv_768 = model.visual_projection(embv_1024)

    embv_768 = F.normalize(embv_768, p=2, dim=-1)
    print("Final CLIP image embedding:", embv_768.shape)

    print(embv_768)

torch.Size([1, 1024, 24, 24])
patch emb:  torch.Size([1, 576, 1024])
emb class:  torch.Size([1024])
torch.Size([1, 1, 1024])
total token:  torch.Size([1, 577, 1024])
position_embeddings: torch.Size([1, 577, 1024])
final_embedding: torch.Size([1, 577, 1024])
visual features shape:  torch.Size([1, 577, 1024])
cls_output before post norm: torch.Size([1, 1024])
EmbV 1024: torch.Size([1, 1024])
Final CLIP image embedding: torch.Size([1, 768])
tensor([[ 8.5212e-03,  2.1927e-02, -1.8225e-02, -4.3406e-03,  3.2806e-02,
         -7.8914e-05, -2.3420e-03, -1.3715e-02, -1.3956e-02, -5.8520e-03,
          3.0947e-02,  4.8188e-02, -2.1490e-02, -1.5646e-02,  4.6379e-02,
          1.4034e-02,  1.8484e-02, -4.8363e-02, -5.8770e-02,  2.7424e-02,
          3.4497e-02, -4.1968e-03,  9.3062e-03,  1.1130e-02,  1.6198e-02,
         -3.8794e-02,  1.5875e-02,  2.4333e-02,  3.0814e-02, -2.9313e-02,
          6.4053e-02,  4.6869e-02,  6.2911e-02,  4.1793e-02, -1.8274e-02,
          9.7640e-03,  2.5834e-02,  7.6615e-03,  3.1808e-02, -1.8798e-02,
          5.2088e-02,  3.7214e-03,  1.7064e-02,  3.0517e-02,  1.0496e-02,
          3.3617e-02, -2.5716e-04,  3.5255e-02, -2.5449e-02, -5.8778e-02,
          3.6676e-02, -3.0354e-02,  1.8145e-02,  6.0463e-02, -4.4745e-02,
          1.8142e-02,  3.6179e-02, -7.3043e-03,  1.5455e-02, -6.8000e-02,
          2.0087e-02,  2.2089e-02,  5.2191e-02, -4.0182e-02, -4.7564e-02,
          2.1196e-02,  1.3896e-02, -1.1802e-02, -3.5522e-02,  2.7103e-02,
         -2.6913e-02, -2.2771e-02,  3.3944e-02, -1.0732e-02,  3.1603e-02,
         -8.1729e-03, -2.7615e-02, -2.3635e-02, -2.9320e-02, -3.6204e-02,
          2.0122e-02,  2.5434e-02, -1.4774e-02, -3.4508e-02,  4.7756e-03,
         -1.8663e-02,  8.5273e-04, -2.1981e-02,  2.4317e-02,  4.9280e-02,
         -5.3452e-02, -1.6981e-02, -3.5409e-02, -5.4068e-02, -8.3121e-03,
          7.3244e-02,  7.5283e-03, -4.1186e-03, -1.5674e-02,  1.6536e-02,
         -5.6414e-02,  3.2418e-04,  5.7479e-03, -1.3768e-03, -2.9689e-02,
          1.2845e-02, -1.6025e-02,  2.1465e-02, -1.0877e-02, -4.6058e-02,
          4.2454e-02, -4.2765e-02,  1.9412e-02,  2.4770e-02, -5.8946e-02,
          5.4659e-03,  2.7721e-06,  2.2107e-02, -2.2151e-02,  2.5825e-02,
          2.8790e-02, -5.7753e-02,  3.4812e-03,  2.4370e-02, -2.3840e-02,
         -2.6366e-02, -1.7382e-02,  1.8509e-02, -1.1308e-02, -6.6405e-04,
          4.3681e-02, -1.1008e-01, -1.1754e-02, -3.0060e-02, -1.2166e-02,
         -3.4213e-02, -2.8196e-02, -1.4963e-02, -3.0889e-02, -5.0424e-03,
         -4.1661e-02, -5.2789e-03,  5.6975e-02,  6.4347e-03,  4.2368e-03,
          2.1311e-02,  5.0773e-04,  4.9917e-02, -2.4787e-02,  1.0500e-02,
          2.7064e-02, -6.1366e-03, -1.1963e-02, -9.7154e-03,  5.8145e-03,
         -6.4094e-03,  3.1693e-02, -4.1149e-02,  2.2600e-02, -5.9256e-03,
          1.1286e-02,  5.7842e-05, -5.1362e-03,  1.2533e-02, -5.2148e-02,
         -3.5237e-02, -2.2362e-02, -1.1165e-02, -4.1037e-02,  1.8601e-02,
          3.1402e-02,  1.9382e-02,  3.5757e-02, -6.9484e-03,  2.3291e-02,
         -1.6447e-02,  2.0998e-02, -8.8306e-02,  8.5365e-02, -1.4086e-02,
          1.3566e-02,  1.4734e-02, -2.4374e-02, -6.5068e-02,  4.7000e-02,
         -2.5742e-02, -4.3694e-04, -4.7634e-02, -2.8907e-02,  7.2346e-02,
          3.6063e-02,  7.9465e-03, -9.4968e-03,  1.9660e-02, -9.2981e-02,
         -4.3197e-02, -1.1310e-02, -7.3743e-04,  2.8545e-02,  4.3872e-02,
          4.0620e-02, -3.6599e-04, -6.3169e-03,  6.7406e-03, -4.1248e-02,
         -1.1404e-03,  9.8100e-04, -6.8468e-02, -2.7545e-02, -4.5449e-03,
         -3.0559e-02,  5.6723e-02, -3.1374e-02,  1.8846e-02, -2.2110e-02,
         -1.5218e-02, -1.4036e-02, -4.5549e-03,  2.7367e-02, -1.0736e-02,
         -3.9285e-03, -5.2702e-02, -4.1040e-02,  1.3590e-02,  5.8150e-03,
         -3.3939e-02,  1.1126e-02, -1.9888e-02, -2.9329e-02, -3.3097e-02,
         -7.1685e-03, -4.4992e-02,  1.2622e-02,  1.8973e-02, -3.4375e-03,
          2.8691e-02,  1.4302e-02, -5.2932e-04,  1.1420e-02, -1.8326e-02,
         -3.9697e-03,  1.3191e-02,  3.4129e-02, -2.4678e-02,  2.5583e-03,
         -3.1101e-02,  1.4628e-02,  1.5217e-02, -3.5681e-02, -1.2140e-03,
          3.5820e-02, -7.3293e-03, -4.6637e-02,  2.8817e-02,  1.1354e-02,
          2.9940e-03,  2.1460e-02,  4.4703e-02,  1.9842e-02, -4.4132e-02,
         -2.7684e-02, -3.8967e-02,  2.2929e-02, -1.3723e-02,  6.0395e-02,
          4.6065e-02, -2.0072e-02, -5.8205e-02, -7.9101e-03,  1.5705e-02,
          2.0547e-02,  3.2709e-02,  9.1133e-03, -8.7240e-03, -5.7786e-02,
         -5.9933e-02, -3.0495e-02,  1.6357e-02,  7.1606e-02, -1.6929e-02,
         -3.2410e-02, -6.2580e-02, -4.2924e-04,  6.1617e-02, -1.1378e-02,
         -1.0943e-02, -6.1527e-02, -2.9949e-02, -9.1285e-02, -1.8133e-02,
         -2.9184e-02,  6.9515e-03,  7.4269e-03, -7.2590e-03, -3.8896e-03,
         -2.4115e-02,  3.1118e-02, -1.2292e-02,  2.6767e-02,  1.2580e-02,
         -2.8198e-02, -3.3476e-03,  2.3782e-02,  5.2538e-03, -3.1140e-02,
         -7.1974e-03, -1.7012e-02, -9.8055e-03,  8.7127e-03, -8.7584e-02,
          1.4944e-02, -1.1123e-02,  3.8056e-04,  3.8846e-02, -3.2429e-02,
          2.1321e-02, -1.1769e-01,  2.3679e-02,  3.0360e-02, -2.4681e-02,
          3.9636e-02,  6.3906e-03, -1.5631e-02, -6.6684e-03,  5.5213e-02,
         -3.1205e-02,  4.3138e-02,  1.3574e-02,  3.6058e-03, -3.1331e-02,
          1.3172e-02,  3.9932e-03, -3.3928e-02, -4.3830e-03,  8.3060e-04,
         -9.1877e-03, -1.9013e-02, -1.1141e-02, -3.7121e-04,  1.1194e-02,
         -3.8297e-03, -1.0132e-02,  6.8281e-03, -7.8449e-04, -4.1202e-03,
         -2.8311e-03, -1.4539e-04,  6.9659e-03, -2.9446e-02,  1.6901e-02,
          3.6712e-02,  2.2671e-02,  9.8726e-03,  3.0636e-02, -1.0005e-02,
         -1.4422e-02,  2.6478e-02,  2.3620e-02, -3.3909e-03, -5.4566e-03,
          9.9354e-03, -1.9428e-02,  1.0177e-02,  5.4418e-02, -5.1406e-03,
          3.3528e-02, -2.1945e-02, -1.2357e-02,  1.8570e-02, -3.3604e-02,
          8.4228e-03, -6.2082e-03,  5.9686e-02,  3.9430e-02, -1.0754e-02,
          1.0367e-02, -2.3344e-02, -2.7451e-03, -3.7560e-02,  1.3881e-02,
          2.7436e-03, -2.3679e-02,  2.1850e-03,  2.1128e-03,  1.2258e-02,
         -2.4723e-02,  6.1777e-02, -2.6882e-02,  2.7021e-02, -3.6578e-02,
          7.9978e-02, -1.4414e-02,  1.2953e-02,  3.1091e-02,  2.6714e-02,
          3.1015e-02, -3.5208e-02,  1.2444e-02, -3.2213e-02, -6.3779e-02,
         -5.0370e-02,  2.9509e-02,  7.6973e-03, -4.3742e-03,  5.6617e-02,
          1.4057e-02, -8.4452e-03,  3.7508e-02,  3.5712e-02,  3.6007e-02,
          8.1374e-03, -1.7108e-02,  2.3017e-03, -3.2968e-01, -2.6283e-03,
         -1.4610e-02, -9.1361e-03,  1.5438e-02,  1.5076e-02,  8.0172e-02,
         -4.8250e-02,  3.5767e-02, -5.1845e-02,  6.9467e-03,  6.9580e-03,
         -3.7522e-02,  2.1150e-02,  4.1849e-02,  1.4687e-03,  7.5376e-03,
          6.7867e-03, -9.5191e-03, -1.8211e-02,  4.1974e-02,  6.0530e-02,
         -1.3024e-02, -4.0919e-02, -2.5074e-02,  2.9426e-02,  5.0553e-02,
          9.9963e-02,  2.6040e-02,  4.7257e-02,  2.5241e-02,  2.7161e-02,
          2.3271e-02,  1.4542e-02, -1.0326e-03, -1.0680e-02, -8.9042e-03,
          3.7704e-02,  2.5640e-02,  2.9327e-02,  2.4988e-02,  7.3347e-02,
         -1.6137e-02,  2.1164e-02,  4.1083e-02, -3.6291e-02,  1.9966e-02,
          4.4094e-04, -4.2602e-02, -1.7444e-02,  1.3086e-01,  5.8640e-02,
         -2.3393e-02,  1.4579e-03,  2.3910e-02, -1.9248e-03, -4.2825e-03,
          3.9528e-02, -1.4862e-02,  2.3380e-02,  2.5181e-02,  2.5439e-02,
         -2.9824e-02, -6.9712e-03,  2.6866e-03, -1.0277e-02,  5.9610e-02,
          2.7285e-02, -3.0199e-02,  3.1833e-02,  8.0628e-04, -2.0924e-02,
          1.2725e-02,  2.5731e-02,  1.9813e-02,  7.8572e-03, -4.5932e-02,
          3.4393e-03,  7.3650e-02, -3.4264e-02, -2.2791e-02,  1.8934e-03,
         -1.5572e-02,  2.3441e-02,  3.8290e-02,  1.3957e-02, -1.8506e-02,
          1.3746e-02, -8.6538e-03,  7.3916e-02, -2.2240e-02,  4.2132e-02,
          8.9598e-05, -2.2433e-02, -9.3379e-03, -8.6030e-03,  1.0375e-02,
          5.9141e-03, -1.4403e-02, -1.9093e-02, -2.0750e-02,  2.1199e-02,
          6.0041e-03, -3.5414e-02,  2.2335e-02, -6.3390e-02,  8.5135e-02,
         -8.3591e-03, -8.7362e-02,  2.4509e-02, -5.2973e-02,  1.9438e-02,
         -3.1056e-02, -1.8995e-02, -4.7442e-02, -3.7524e-02, -5.1272e-02,
          3.5168e-02,  8.8468e-03, -1.6682e-02,  4.8288e-02, -2.8398e-02,
         -2.4646e-02,  1.2206e-02,  1.6778e-03, -2.4149e-02,  1.4059e-02,
         -4.1735e-03,  3.4950e-03, -4.6794e-02, -3.2057e-03, -3.0994e-02,
          2.1905e-02, -2.1151e-02,  2.4689e-02, -1.9387e-02, -3.3154e-02,
          1.4301e-02,  5.2631e-02,  5.2690e-03,  3.8857e-02,  4.4537e-02,
         -2.3778e-02,  3.3761e-02, -2.6086e-02,  5.1675e-02, -1.4657e-02,
          1.3255e-01,  1.0713e-02,  1.7940e-02, -6.0465e-03,  1.5664e-02,
         -2.7093e-02, -3.7937e-02,  2.0418e-02,  5.4127e-02,  2.0695e-04,
         -9.2273e-03, -4.2439e-02, -4.8940e-02,  1.9800e-03, -1.3575e-02,
         -2.1838e-02,  2.8325e-03, -3.9993e-02, -1.2494e-02,  6.2597e-02,
          3.5029e-02,  8.9249e-03,  2.4580e-02,  3.3176e-02,  8.0796e-02,
          9.2919e-03,  1.0795e-02, -1.7623e-03, -3.2345e-02, -1.6050e-02,
         -4.1308e-02,  7.5319e-04,  1.1236e-03,  1.6621e-02, -4.6626e-02,
         -1.2596e-02,  4.0466e-03,  2.9266e-02,  2.4394e-02, -4.7086e-02,
          1.8970e-02, -9.6438e-03, -1.8103e-02, -1.1230e-02,  4.9591e-03,
          7.3910e-02, -6.2821e-03,  2.6251e-02,  6.1972e-03,  1.6586e-02,
          3.2528e-03,  2.5928e-02,  5.3649e-02,  4.3558e-02,  2.5215e-02,
         -7.6208e-03,  4.2115e-02, -2.0782e-02,  4.8051e-02, -3.3632e-02,
         -1.6217e-02,  3.4521e-02, -1.0478e-02, -4.0580e-02,  2.3526e-02,
         -6.0785e-02,  1.8625e-02, -3.4852e-02,  2.2815e-02, -1.3427e-02,
          1.6603e-02, -1.8074e-02,  3.6340e-02,  1.1153e-02,  5.6669e-02,
         -7.2462e-02, -1.6099e-02,  1.0533e-02,  4.8137e-03,  1.0043e-02,
          1.6662e-02,  7.5160e-03,  2.2597e-02, -6.3901e-02,  3.4492e-01,
         -1.5571e-03,  3.4527e-03,  2.1169e-02, -8.7765e-03, -2.0643e-02,
          2.4250e-02,  2.2408e-02,  2.0412e-02,  1.0381e-02,  2.9677e-02,
         -4.3676e-02,  2.1516e-02,  4.3213e-02,  1.4337e-02, -5.6810e-02,
         -4.4408e-03,  3.8949e-02,  6.4541e-03, -1.1253e-02,  3.3781e-02,
         -1.8848e-03,  2.4062e-02, -1.3531e-02, -1.4025e-02,  1.2073e-02,
          3.5595e-03, -2.1159e-02,  5.0822e-02, -1.2430e-02,  5.2288e-03,
         -3.1044e-02,  1.1819e-02,  3.0320e-03,  4.0983e-02, -1.5763e-02,
         -7.9191e-03,  1.3937e-02, -1.3698e-02, -5.5947e-02,  5.9586e-02,
         -2.9758e-02, -5.8865e-02, -3.8983e-02,  9.9852e-03, -1.0561e-02,
         -3.6719e-02,  3.2573e-02, -2.1074e-02, -1.4604e-02, -8.0714e-04,
         -2.1047e-02,  5.6992e-02,  1.2099e-04, -3.6840e-02, -3.2087e-02,
         -1.9385e-02, -2.8865e-02,  3.0134e-02,  4.6055e-02, -2.3646e-02,
         -1.6051e-02,  4.2791e-02,  4.2867e-02,  7.2248e-03, -3.4806e-02,
          7.2406e-03, -1.5827e-02,  6.7227e-02,  2.3715e-02, -7.1545e-03,
          4.7018e-02, -8.7808e-03,  1.9522e-02, -2.6803e-02,  1.0788e-02,
          9.1984e-03, -1.4480e-02,  3.2481e-02, -2.2644e-02, -4.9719e-02,
          5.5368e-03, -5.0607e-02, -1.1172e-02,  4.2885e-03,  3.5094e-02,
         -4.4034e-03,  1.4577e-02, -3.5955e-02, -7.4408e-02, -1.0525e-02,
         -2.6187e-03, -1.1180e-02, -2.0788e-02, -2.0269e-03, -3.8673e-02,
         -4.1345e-03,  4.6396e-03, -1.5659e-02, -1.1600e-02, -4.1068e-02,
          2.0619e-02, -4.7136e-02,  6.3212e-03,  1.0742e-02, -1.9897e-02,
         -1.9499e-02, -4.3426e-03, -5.0580e-03, -3.3005e-02,  8.4027e-03,
          2.8867e-02,  3.3819e-02, -1.6872e-02, -2.3216e-02,  4.9364e-02,
         -8.2797e-03,  1.9687e-02,  4.6754e-02,  3.2068e-02,  2.5983e-03,
         -1.5708e-02, -3.0732e-02, -5.0951e-03]])

In [144]:
sample_query_text = "My Dog Step on a Bee"
with torch.no_grad():
    text_inputs = processor(
        text=[sample_query_text],
        return_tensors="pt",
        padding="max_length",
        max_length=77,
        truncation=True
    )

    input_ids = text_inputs["input_ids"].to(DEVICE)
    attention_mask = text_inputs["attention_mask"].to(DEVICE)

    text_outputs = model.text_model(
        input_ids=input_ids,
        attention_mask=attention_mask,
        output_hidden_states=True,
        return_dict=True
    )

    text_features = text_outputs.last_hidden_state
    embt = text_outputs.pooler_output

    print("input_ids:", input_ids.shape)
    print("attention_mask:", attention_mask.shape)
    print("text_features:", text_features.shape)
    print("EmbT:", embt.shape)

input_ids: torch.Size([1, 77])
attention_mask: torch.Size([1, 77])
text_features: torch.Size([1, 77, 768])
EmbT: torch.Size([1, 768])

In [145]:
def image_embedder(img_path: str):
    image = Image.open(img_path).convert("RGB")

    inputs = processor(images=image, return_tensors="pt")
    pixel_values = inputs["pixel_values"].to(DEVICE)

    with torch.no_grad():
        vision = model.vision_model
        emb = vision.embeddings
        
        patch_grid = emb.patch_embedding(pixel_values)
        patch_embeddings = patch_grid.flatten(2).transpose(1, 2)

        batch_size = patch_embeddings.shape[0]
        cls_token = emb.class_embedding.expand(batch_size, 1, -1)

        token_emb = torch.cat([cls_token, patch_embeddings], dim=1)

        position_ids = torch.arange(token_emb.shape[1], device=pixel_values.device).unsqueeze(0)
        position_embeddings = emb.position_embedding(position_ids)

        final_embedding = token_emb + position_embeddings

        hidden_states = vision.pre_layrnorm(final_embedding)

        encoder_outputs = vision.encoder(
            inputs_embeds=hidden_states,
            output_hidden_states=True,
            return_dict=True
        )

        visual_features = encoder_outputs.last_hidden_state

        cls_output = visual_features[:, 0, :]
        embv_1024 = vision.post_layernorm(cls_output)

        embv_768 = model.visual_projection(embv_1024)
        embv_768 = F.normalize(embv_768, p=2, dim=-1)

        return embv_768

In [146]:
def text_embedder(query: str):
    with torch.no_grad():
        text_inputs = processor(
            text=[query],
            return_tensors="pt",
            padding="max_length",
            max_length=77,
            truncation=True
        )

        input_ids = text_inputs["input_ids"].to(DEVICE)
        attention_mask = text_inputs["attention_mask"].to(DEVICE)

        text_outputs = model.text_model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            return_dict=True
        )

        embt = text_outputs.pooler_output        
        embt = model.text_projection(embt)       
        embt = F.normalize(embt, p=2, dim=-1)

        return embt

In [147]:
image_embedder(IMAGE_DATA_DIR / "682716753374351360.jpg").shape

torch.Size([1, 768])

In [148]:
text_embedder("My Dog Step On A Bee").shape

torch.Size([1, 768])

In [149]:
image_urls = []
for image_name in os.listdir(IMAGE_DATA_DIR):
    full_path = IMAGE_DATA_DIR / image_name
    image_urls.append(full_path)
len(image_urls)

24635

In [150]:
df_train.head(5)

,image_id,text,label
0,840006160660983809,<user> thanks for showing up for our appointme...,1
1,908913372199915520,haha .,1
2,916496521406726145,i love waiting <num> min for a cab - such shor...,1
3,916364004129304576,22 super funny quotes <user>,1
4,853866052589154304,goog morning,1

In [151]:
#df_train = df_train[:10]
df_train = df_train.reset_index(drop=True)

In [152]:
metadata_rows = []
embv_list = []
embt_list = []

for index, row in tqdm(df_train.iterrows(), total=len(df_train)):
    image_full_path = IMAGE_DATA_DIR / f"{str(row['image_id'])}.jpg"
    text = row["text"]
    label = row["label"]

    embt = text_embedder(text)
    embv = image_embedder(image_full_path)
    embv_list.append(embv)
    embt_list.append(embt)

    metadata_rows.append({
        "image_path": str(image_full_path),
        "text": text,
        "label": label
    })

metadata_df = pd.DataFrame(metadata_rows)

embv_array = np.stack(embv_list)
embt_array = np.stack(embt_list)


metadata_df.to_csv(os.path.join(OUTPUT_DIR, "train_metadata.csv"), index=False)
np.save(os.path.join(OUTPUT_DIR, "train_embv.npy"), embv_array)
np.save(os.path.join(OUTPUT_DIR, "train_embt.npy"), embt_array)

100%|██████████| 19816/19816 [6:28:41<00:00,  1.18s/it]

In [ ]:
metadata_df = pd.read_csv(OUTPUT_DIR / "train_metadata.csv")
train_embv = np.load(OUTPUT_DIR / "train_embv.npy").astype("float32")
train_embt = np.load(OUTPUT_DIR / "train_embt.npy").astype("float32")

In [ ]:
def retrieve_top_k(query_embedding, db_embeddings, metadata_df, top_k=5, exclude_image_id=None):
    query_vec = query_embedding.squeeze(0).detach().cpu().numpy().astype("float32")

    scores = db_embeddings @ query_vec

    if exclude_image_id is not None:
        mask = metadata_df["image_id"].astype(str) == str(exclude_image_id)
        scores[mask.values] = -np.inf

    top_indices = np.argsort(scores)[-top_k:][::-1]

    results = metadata_df.iloc[top_indices].copy()
    results["score"] = scores[top_indices]

    return results